module.exports = [
          {
            name: "Set 1 – Autumn City",
            cards: [
              {
                name: "Paper Cup",
                emoji: "☕",
                img: "images/set01-autumn-city-paper-cup.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Newsstand",
                emoji: "📰",
                img: "images/set01-autumn-city-newsstand.webp",
                bonus: 1,
                bg: "green-bg",
              },
              {
                name: "Bike Rack",
                emoji: "🚲",
                img: "images/set01-autumn-city-bike-rack.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Balcony",
                emoji: "🏢",
                img: "images/set01-autumn-city-balcony.webp",
                bonus: 1,
                bg: "",
              },
              {
                name: "Road Barrier",
                emoji: "🚧",
                img: "images/set01-autumn-city-road-barrier.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Tram",
                emoji: "🚋",
                img: "images/set01-autumn-city-tram.webp",
                bonus: 1,
                bg: "pink-bg",
              },
              {
                name: "Streetlamp",
                emoji: "🏮",
                img: "images/set01-autumn-city-streetlamp.webp",
                bonus: 1,
                bg: "teal-bg",
              },
              {
                name: "Clock Tower",
                emoji: "🕰️",
                img: "images/set01-autumn-city-clock-tower.webp",
                bonus: 1,
                bg: "green-bg",
              },
              {
                name: "Bridge",
                emoji: "🌉",
                img: "images/set01-autumn-city-bridge.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Paper Boat",
                emoji: "⛵",
                img: "images/set01-autumn-city-paper-boat.webp",
                bonus: 2,
                bg: "",
              },
            ],
          },
          {
            name: "Set 2 – Comfort",
            cards: [
              {
                name: "Firewood",
                emoji: "🪵",
                img: "images/set02-comfort-firewood.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Slippers",
                emoji: "🥿",
                img: "images/set02-comfort-slippers.webp",
                bonus: 1,
                bg: "green-bg",
              },
              {
                name: "Knitted Throw",
                emoji: "🧶",
                img: "images/set02-comfort-knitted-throw.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Rocking Chair",
                emoji: "🪑",
                img: "images/set02-comfort-rocking-chair.webp",
                bonus: 1,
                bg: "",
              },
              {
                name: "Spiced Tea",
                emoji: "🍵",
                img: "images/set02-comfort-spiced-tea.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Sofa",
                emoji: "🛋️",
                img: "images/set02-comfort-sofa.webp",
                bonus: 1,
                bg: "pink-bg",
              },
              {
                name: "Stovetop Kettle",
                emoji: "🫖",
                img: "images/set02-comfort-stovetop-kettle.webp",
                bonus: 1,
                bg: "teal-bg",
              },
              {
                name: "Robe",
                emoji: "👘",
                img: "images/set02-comfort-robe.webp",
                bonus: 1,
                bg: "green-bg",
              },
              {
                name: "Lamp",
                emoji: "💡",
                img: "images/set02-comfort-lamp.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Candle",
                emoji: "🕯️",
                img: "images/set02-comfort-candle.webp",
                bonus: 1,
                bg: "",
              },
            ],
          },
          {
            name: "Set 3 – Forest",
            cards: [
              {
                name: "Acorn",
                emoji: "🌰",
                img: "images/set03-forest-acorn.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Forest Trail",
                emoji: "🥾",
                img: "images/set03-forest-forest-trail.webp",
                bonus: 1,
                bg: "green-bg",
              },
              {
                name: "Maple Leaf",
                emoji: "🍁",
                img: "images/set03-forest-maple-leaf.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Pinecones",
                emoji: "🌲",
                img: "images/set03-forest-pinecones.webp",
                bonus: 1,
                bg: "",
              },
              {
                name: "Toadstool",
                emoji: "🍄",
                img: "images/set03-forest-toadstool.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Fallen Log",
                emoji: "🪵",
                img: "images/set03-forest-fallen-log.webp",
                bonus: 1,
                bg: "pink-bg",
              },
              {
                name: "Forest Brook",
                emoji: "🏞️",
                img: "images/set03-forest-forest-brook.webp",
                bonus: 1,
                bg: "teal-bg",
              },
              {
                name: "Flying Geese",
                emoji: "🪿",
                img: "images/set03-forest-flying-geese.webp",
                bonus: 1,
                bg: "green-bg",
              },
              {
                name: "Boulder",
                emoji: "🪨",
                img: "images/set03-forest-boulder.webp",
                bonus: 3,
                bg: "purple-bg",
              },
              {
                name: "Rowan Berries",
                emoji: "🍒",
                img: "images/set03-forest-rowan-berries.webp",
                bonus: 4,
                bg: "",
              },
            ],
          },
          {
            name: "Set 4 – School Life",
            cards: [
              {
                name: "Chalkboard",
                emoji: "📋",
                img: "images/set04-school-life-chalkboard.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Bookcase",
                emoji: "📚",
                img: "images/set04-school-life-bookcase.webp",
                bonus: 1,
                bg: "green-bg",
              },
              {
                name: "Backpack",
                emoji: "🎒",
                img: "images/set04-school-life-backpack.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Ball",
                emoji: "⚽",
                img: "images/set04-school-life-ball.webp",
                bonus: 1,
                bg: "",
              },
              {
                name: "Test Tubes",
                emoji: "🧪",
                img: "images/set04-school-life-test-tubes.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Globe",
                emoji: "🌍",
                img: "images/set04-school-life-globe.webp",
                bonus: 1,
                bg: "pink-bg",
              },
              {
                name: "Desk",
                emoji: "🪑",
                img: "images/set04-school-life-desk.webp",
                bonus: 1,
                bg: "teal-bg",
              },
              {
                name: "Campus",
                emoji: "🏫",
                img: "images/set04-school-life-campus.webp",
                bonus: 2,
                bg: "green-bg",
              },
              {
                name: "Mug",
                emoji: "☕",
                img: "images/set04-school-life-mug.webp",
                bonus: 3,
                bg: "purple-bg",
              },
              {
                name: "Stationery",
                emoji: "✏️",
                img: "images/set04-school-life-stationery.webp",
                bonus: 4,
                bg: "",
              },
            ],
          },
          {
            name: "Set 5 – Scary Tales",
            cards: [
              {
                name: "Toy Spider",
                emoji: "🕷️",
                img: "images/set05-scary-tales-toy-spider.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Crow",
                emoji: "🐦‍⬛",
                img: "images/set05-scary-tales-crow.webp",
                bonus: 2,
                bg: "green-bg",
              },
              {
                name: "Ghost",
                emoji: "👻",
                img: "images/set05-scary-tales-ghost.webp",
                bonus: 1,
                bg: "orange-bg",
              },
              {
                name: "Scarecrow",
                emoji: "🧑‍🌾",
                img: "images/set05-scary-tales-scarecrow.webp",
                bonus: 2,
                bg: "",
              },
              {
                name: "Old Tree",
                emoji: "🌳",
                img: "images/set05-scary-tales-old-tree.webp",
                bonus: 2,
                bg: "orange-bg",
              },
              {
                name: "Haunted House",
                emoji: "🏚️",
                img: "images/set05-scary-tales-haunted-house.webp",
                bonus: 1,
                bg: "pink-bg",
              },
              {
                name: "Cauldron",
                emoji: "🫕",
                img: "images/set05-scary-tales-cauldron.webp",
                bonus: 1,
                bg: "teal-bg",
              },
              {
                name: "Dungeon",
                emoji: "🏰",
                img: "images/set05-scary-tales-dungeon.webp",
                bonus: 2,
                bg: "green-bg",
              },
              {
                name: "Pumpkin",
                emoji: "🎃",
                img: "images/set05-scary-tales-pumpkin.webp",
                bonus: 2,
                bg: "purple-bg",
              },
              {
                name: "Gate",
                emoji: "🚪",
                img: "images/set05-scary-tales-gate.webp",
                bonus: 4,
                bg: "",
              },
            ],
          },
          {
            name: "Set 6 – Rainy Day",
            cards: [
              {
                name: "Thunderstorm",
                emoji: "⛈️",
                img: "images/set06-rainy-day-thunderstorm.webp",
                bonus: 2,
                bg: "purple-bg",
              },
              {
                name: "Scarf",
                emoji: "🧣",
                img: "images/set06-rainy-day-scarf.webp",
                bonus: 2,
                bg: "green-bg",
              },
              {
                name: "Thermometer",
                emoji: "🌡️",
                img: "images/set06-rainy-day-thermometer.webp",
                bonus: 3,
                bg: "orange-bg",
              },
              {
                name: "Wind Vane",
                emoji: "🧭",
                img: "images/set06-rainy-day-wind-vane.webp",
                bonus: 2,
                bg: "",
              },
              {
                name: "Umbrella",
                emoji: "☂️",
                img: "images/set06-rainy-day-umbrella.webp",
                bonus: 2,
                bg: "orange-bg",
              },
              {
                name: "Rain Hat",
                emoji: "👒",
                img: "images/set06-rainy-day-rain-hat.webp",
                bonus: 2,
                bg: "pink-bg",
              },
              {
                name: "Dew",
                emoji: "💧",
                img: "images/set06-rainy-day-dew.webp",
                bonus: 3,
                bg: "teal-bg",
              },
              {
                name: "Drying Rack",
                emoji: "🧺",
                img: "images/set06-rainy-day-drying-rack.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Puddle",
                emoji: "💦",
                img: "images/set06-rainy-day-puddle.webp",
                bonus: 5,
                bg: "purple-bg",
              },
              {
                name: "Rainbow",
                emoji: "🌈",
                img: "images/set06-rainy-day-rainbow.webp",
                bonus: 5,
                bg: "",
              },
            ],
          },
          {
            name: "Set 7 – Harvest",
            cards: [
              {
                name: "Apple Bucket",
                emoji: "🍎",
                img: "images/set07-harvest-apple-bucket.webp",
                bonus: 1,
                bg: "purple-bg",
              },
              {
                name: "Sheaf",
                emoji: "🌾",
                img: "images/set07-harvest-sheaf.webp",
                bonus: 3,
                bg: "green-bg",
              },
              {
                name: "Barn",
                emoji: "🏠",
                img: "images/set07-harvest-barn.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Pitchfork",
                emoji: "🔱",
                img: "images/set07-harvest-pitchfork.webp",
                bonus: 3,
                bg: "",
              },
              {
                name: "Corn",
                emoji: "🌽",
                img: "images/set07-harvest-corn.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Carrots",
                emoji: "🥕",
                img: "images/set07-harvest-carrots.webp",
                bonus: 3,
                bg: "pink-bg",
              },
              {
                name: "Pumpkin Cart",
                emoji: "🛒",
                img: "images/set07-harvest-pumpkin-cart.webp",
                bonus: 3,
                bg: "teal-bg",
              },
              {
                name: "Cabbage",
                emoji: "🥬",
                img: "images/set07-harvest-cabbage.webp",
                bonus: 5,
                bg: "green-bg",
              },
              {
                name: "Berries",
                emoji: "🍓",
                img: "images/set07-harvest-berries.webp",
                bonus: 5,
                bg: "purple-bg",
              },
              {
                name: "Harvester",
                emoji: "🚜",
                img: "images/set07-harvest-harvester.webp",
                bonus: 5,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 8 – Bedtime",
            cards: [
              {
                name: "Bed",
                emoji: "🛏️",
                img: "images/set08-bedtime-bed.webp",
                bonus: 3,
                bg: "purple-bg",
              },
              {
                name: "Sleep Mask",
                emoji: "😴",
                img: "images/set08-bedtime-sleep-mask.webp",
                bonus: 3,
                bg: "green-bg",
              },
              {
                name: "Teddy Bear",
                emoji: "🧸",
                img: "images/set08-bedtime-teddy-bear.webp",
                bonus: 3,
                bg: "orange-bg",
              },
              {
                name: "Clock",
                emoji: "🕐",
                img: "images/set08-bedtime-clock.webp",
                bonus: 3,
                bg: "",
              },
              {
                name: "Storybook",
                emoji: "📖",
                img: "images/set08-bedtime-storybook.webp",
                bonus: 3,
                bg: "orange-bg",
              },
              {
                name: "Owl",
                emoji: "🦉",
                img: "images/set08-bedtime-owl.webp",
                bonus: 3,
                bg: "pink-bg",
              },
              {
                name: "Dreamcatcher",
                emoji: "🪶",
                img: "images/set08-bedtime-dreamcatcher.webp",
                bonus: 3,
                bg: "teal-bg",
              },
              {
                name: "Moon",
                emoji: "🌙",
                img: "images/set08-bedtime-moon.webp",
                bonus: 5,
                bg: "green-bg",
              },
              {
                name: "Humidifier",
                emoji: "💨",
                img: "images/set08-bedtime-humidifier.webp",
                bonus: 5,
                bg: "purple-bg",
              },
              {
                name: "Sleeping Man",
                emoji: "🛌",
                img: "images/set08-bedtime-sleeping-man.webp",
                bonus: 5,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 9 – Costumes",
            cards: [
              {
                name: "Fangs",
                emoji: "🧛",
                img: "images/set09-costumes-fangs.webp",
                bonus: 3,
                bg: "purple-bg",
              },
              {
                name: "Horns",
                emoji: "😈",
                img: "images/set09-costumes-horns.webp",
                bonus: 3,
                bg: "green-bg",
              },
              {
                name: "Vampire Costume",
                emoji: "🧛‍♂️",
                img: "images/set09-costumes-vampire-costume.webp",
                bonus: 3,
                bg: "orange-bg",
              },
              {
                name: "Face Paints",
                emoji: "🎨",
                img: "images/set09-costumes-face-paints.webp",
                bonus: 3,
                bg: "",
              },
              {
                name: "Jester Hat",
                emoji: "🤡",
                img: "images/set09-costumes-jester-hat.webp",
                bonus: 3,
                bg: "orange-bg",
              },
              {
                name: "Cloak",
                emoji: "🧥",
                img: "images/set09-costumes-cloak.webp",
                bonus: 3,
                bg: "pink-bg",
              },
              {
                name: "Ring",
                emoji: "💍",
                img: "images/set09-costumes-ring.webp",
                bonus: 3,
                bg: "teal-bg",
              },
              {
                name: "Wizard Hat",
                emoji: "🧙",
                img: "images/set09-costumes-wizard-hat.webp",
                bonus: 3,
                bg: "green-bg",
              },
              {
                name: "Mummy",
                emoji: "🧟",
                img: "images/set09-costumes-mummy.webp",
                bonus: 3,
                bg: "purple-bg",
                gold: true,
              },
              {
                name: "Makeup Artist",
                emoji: "💄",
                img: "images/set09-costumes-makeup-artist.webp",
                bonus: 3,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 10 – Pastimes",
            cards: [
              {
                name: "Painting",
                emoji: "🎨",
                img: "images/set10-pastimes-painting.webp",
                bonus: 3,
                bg: "purple-bg",
              },
              {
                name: "Teepee",
                emoji: "🏕️",
                img: "images/set10-pastimes-teepee.webp",
                bonus: 3,
                bg: "green-bg",
              },
              {
                name: "Block Tower",
                emoji: "🧱",
                img: "images/set10-pastimes-block-tower.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Gramophone",
                emoji: "🎼",
                img: "images/set10-pastimes-gramophone.webp",
                bonus: 3,
                bg: "",
              },
              {
                name: "Pressed Flower",
                emoji: "🌸",
                img: "images/set10-pastimes-pressed-flower.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Pottery",
                emoji: "🏺",
                img: "images/set10-pastimes-pottery.webp",
                bonus: 3,
                bg: "pink-bg",
              },
              {
                name: "Yarn Ball",
                emoji: "🧶",
                img: "images/set10-pastimes-yarn-ball.webp",
                bonus: 3,
                bg: "teal-bg",
              },
              {
                name: "Puzzle",
                emoji: "🧩",
                img: "images/set10-pastimes-puzzle.webp",
                bonus: 3,
                bg: "green-bg",
              },
              {
                name: "Knitting",
                emoji: "🪡",
                img: "images/set10-pastimes-knitting.webp",
                bonus: 4,
                bg: "purple-bg",
                gold: true,
              },
              {
                name: "Park Stroll",
                emoji: "🚶",
                img: "images/set10-pastimes-park-stroll.webp",
                bonus: 4,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 11 – Diwali",
            cards: [
              {
                name: "Oil Lamp",
                emoji: "🪔",
                img: "images/set11-diwali-oil-lamp.webp",
                bonus: 3,
                bg: "purple-bg",
              },
              {
                name: "Elephant",
                emoji: "🐘",
                img: "images/set11-diwali-elephant.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Rangoli",
                emoji: "🌺",
                img: "images/set11-diwali-rangoli.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Incense Sticks",
                emoji: "🧿",
                img: "images/set11-diwali-incense-sticks.webp",
                bonus: 4,
                bg: "",
              },
              {
                name: "Lights",
                emoji: "💡",
                img: "images/set11-diwali-lights.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Laddu",
                emoji: "🍡",
                img: "images/set11-diwali-laddu.webp",
                bonus: 4,
                bg: "pink-bg",
              },
              {
                name: "Paper Lantern",
                emoji: "🏮",
                img: "images/set11-diwali-paper-lantern.webp",
                bonus: 4,
                bg: "teal-bg",
              },
              {
                name: "Sweets",
                emoji: "🍬",
                img: "images/set11-diwali-sweets.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Decorating",
                emoji: "🎊",
                img: "images/set11-diwali-decorating.webp",
                bonus: 4,
                bg: "purple-bg",
                gold: true,
              },
              {
                name: "Fireworks",
                emoji: "🎆",
                img: "images/set11-diwali-fireworks.webp",
                bonus: 5,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 12 – Sweets",
            cards: [
              {
                name: "Candy",
                emoji: "🍬",
                img: "images/set12-sweets-candy.webp",
                bonus: 4,
                bg: "purple-bg",
              },
              {
                name: "Candy Bowl",
                emoji: "🥣",
                img: "images/set12-sweets-candy-bowl.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Lollipop",
                emoji: "🍭",
                img: "images/set12-sweets-lollipop.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Bat Cookies",
                emoji: "🦇",
                img: "images/set12-sweets-bat-cookies.webp",
                bonus: 4,
                bg: "",
              },
              {
                name: "Caramel Apple",
                emoji: "🍯",
                img: "images/set12-sweets-caramel-apple.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Gummy Worms",
                emoji: "🐛",
                img: "images/set12-sweets-gummy-worms.webp",
                bonus: 4,
                bg: "pink-bg",
              },
              {
                name: "Vampire Cookie",
                emoji: "🍪",
                img: "images/set12-sweets-vampire-cookie.webp",
                bonus: 4,
                bg: "teal-bg",
              },
              {
                name: "Cupcake",
                emoji: "🧁",
                img: "images/set12-sweets-cupcake.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Trick or Treat",
                emoji: "🎃",
                img: "images/set12-sweets-trick-or-treat.webp",
                bonus: 4,
                bg: "purple-bg",
                gold: true,
              },
              {
                name: "Baking",
                emoji: "👨‍🍳",
                img: "images/set12-sweets-baking.webp",
                bonus: 4,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 13 – Fall Feast",
            cards: [
              {
                name: "Gravy Boat",
                emoji: "🥣",
                img: "images/set13-fall-feast-gravy-boat.webp",
                bonus: 4,
                bg: "purple-bg",
              },
              {
                name: "Leaf Bouquet",
                emoji: "🍂",
                img: "images/set13-fall-feast-leaf-bouquet.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Cornucopia",
                emoji: "🧺",
                img: "images/set13-fall-feast-cornucopia.webp",
                bonus: 5,
                bg: "orange-bg",
              },
              {
                name: "Pilgrim Hat",
                emoji: "🎩",
                img: "images/set13-fall-feast-pilgrim-hat.webp",
                bonus: 4,
                bg: "",
              },
              {
                name: "Pie",
                emoji: "🥧",
                img: "images/set13-fall-feast-pie.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Goblet",
                emoji: "🍷",
                img: "images/set13-fall-feast-goblet.webp",
                bonus: 4,
                bg: "pink-bg",
              },
              {
                name: "Table Setting",
                emoji: "🍽️",
                img: "images/set13-fall-feast-table-setting.webp",
                bonus: 4,
                bg: "teal-bg",
              },
              {
                name: "Wreath",
                emoji: "🌿",
                img: "images/set13-fall-feast-wreath.webp",
                bonus: 5,
                bg: "green-bg",
                gold: true,
              },
              {
                name: "Turkey",
                emoji: "🦃",
                img: "images/set13-fall-feast-turkey.webp",
                bonus: 5,
                bg: "purple-bg",
                gold: true,
              },
              {
                name: "Parade",
                emoji: "🎉",
                img: "images/set13-fall-feast-parade.webp",
                bonus: 5,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 14 – Sale Day",
            cards: [
              {
                name: "Gift Box",
                emoji: "🎁",
                img: "images/set14-sale-day-gift-box.webp",
                bonus: 5,
                bg: "purple-bg",
              },
              {
                name: "Balloon Arch",
                emoji: "🎈",
                img: "images/set14-sale-day-balloon-arch.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Wallet",
                emoji: "👛",
                img: "images/set14-sale-day-wallet.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Raffle Machine",
                emoji: "🎰",
                img: "images/set14-sale-day-raffle-machine.webp",
                bonus: 5,
                bg: "",
              },
              {
                name: "Sale Sign",
                emoji: "🏷️",
                img: "images/set14-sale-day-sale-sign.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "On Sale",
                emoji: "🔖",
                img: "images/set14-sale-day-on-sale.webp",
                bonus: 4,
                bg: "pink-bg",
              },
              {
                name: "Shopping Basket",
                emoji: "🛒",
                img: "images/set14-sale-day-shopping-basket.webp",
                bonus: 4,
                bg: "teal-bg",
              },
              {
                name: "Sale",
                emoji: "💰",
                img: "images/set14-sale-day-sale.webp",
                bonus: 4,
                bg: "green-bg",
                gold: true,
              },
              {
                name: "Online Deals",
                emoji: "💻",
                img: "images/set14-sale-day-online-deals.webp",
                bonus: 4,
                bg: "purple-bg",
                gold: true,
              },
              {
                name: "Shopping",
                emoji: "🛍️",
                img: "images/set14-sale-day-shopping.webp",
                bonus: 4,
                bg: "",
                gold: true,
              },
            ],
          },
          {
            name: "Set 15 – Grape Fair",
            cards: [
              {
                name: "Grapes",
                emoji: "🍇",
                img: "images/set15-grape-fair-grapes.webp",
                bonus: 4,
                bg: "purple-bg",
              },
              {
                name: "Straw Hat",
                emoji: "👒",
                img: "images/set15-grape-fair-straw-hat.webp",
                bonus: 4,
                bg: "green-bg",
              },
              {
                name: "Drum",
                emoji: "🥁",
                img: "images/set15-grape-fair-drum.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Cheese Plate",
                emoji: "🧀",
                img: "images/set15-grape-fair-cheese-plate.webp",
                bonus: 5,
                bg: "",
              },
              {
                name: "Grape Press",
                emoji: "🛠️",
                img: "images/set15-grape-fair-grape-press.webp",
                bonus: 4,
                bg: "orange-bg",
              },
              {
                name: "Windmill",
                emoji: "🌬️",
                img: "images/set15-grape-fair-windmill.webp",
                bonus: 4,
                bg: "pink-bg",
              },
              {
                name: "Grape Picking",
                emoji: "🙌",
                img: "images/set15-grape-fair-grape-picking.webp",
                bonus: 4,
                bg: "teal-bg",
                gold: true,
              },
              {
                name: "Drumbeat",
                emoji: "🎵",
                img: "images/set15-grape-fair-drumbeat.webp",
                bonus: 4,
                bg: "green-bg",
                gold: true,
              },
              {
                name: "Carousel",
                emoji: "🎠",
                img: "images/set15-grape-fair-carousel.webp",
                bonus: 4,
                bg: "purple-bg",
                gold: true,
              },
              {
                name: "Dance",
                emoji: "💃",
                img: "images/set15-grape-fair-dance.webp",
                bonus: 4,
                bg: "",
                gold: true,
              },
            ],
          },
        ]